from PyQt6.QtCore import QLocale

TEXTS = {
    "en": {
        "f1_help_title": "CYBERCOMMANDER CORE COMMAND MANUAL",
        "prop_title": "METADATA PROPERTIES",
        "prop_path": "Absolute Path:",
        "prop_size": "Sector Size:",
        "prop_created": "Creation Epoch:",
        "prop_modified": "Last Mutation:",
        "prop_type": "Node Type:",
        "editor_title": "CYBERNETIC RAW TEXT EDITOR",
        "editor_save": "COMMIT CHANGES",
        "editor_saved": "COMMIT OK. File data sync completed.",
        "hidden_toggled": "Hidden files toggled.",
        "flat_toggled": "Flat list view toggled.",
        "swap_panes": "Panels directory structure swapped.",
        "tab_opened": "New navigation tab initialized.",
        "tab_closed": "Navigation tab terminated.",
        "no_selection": "ERROR: Select at least one node to perform this operation.",
        "file_created": "New node generated successfully.",
        "create_file_prompt": "Enter Filename to create (e.g. log.txt):",
        "delete_confirm": "WARNING: Delete selected items permanently? (Recycle Bin bypass)\n\n",
        "f3_view": "F1 Help  |  F2 Reread  |  F3 View  |  F4 Edit  |  F5 Copy  |  F6 Move  |  F7 Mkdir  |  F8 Delete",
        "f3_view_btn": "F3 VIEW",
        "f4_hash": "F4 EDIT",
        "f5_copy": "F5 COPY",
        "f6_move": "F6 MOVE",
        "f7_mkdir": "F7 MKDIR",
        "f8_shred": "F8 DELETE",
        "active_left": "SYSTEM READY. ACTIVE SECTOR: LEFT PANE",
        "active_right": "SYSTEM READY. ACTIVE SECTOR: RIGHT PANE",
        "system_ready": "SYSTEM READY.",
        "search_title": "CYBER SEARCH ENGINE",
        "search_pattern": "Search Pattern (e.g. *.txt):",
        "search_content": "Containing Text (Optional):",
        "search_btn": "EXECUTE SEARCH",
        "multi_rename_title": "MULTI-RENAME SEQUENCER",
        "mr_prefix": "Prefix Pattern:",
        "mr_suffix": "Suffix Pattern:",
        "mr_replace_src": "Search For:",
        "mr_replace_dst": "Replace With:",
        "mr_counter": "Enable Counter [1, 2, 3...]:",
        "mr_btn": "EXECUTE RENAME PROTOCOL",
        "zip_pack_title": "ZIP PACK PROTOCOL",
        "zip_unpack_title": "ZIP EXTRACT PROTOCOL",
        "bookmarks_title": "SECTOR BOOKMARKS",
        "btn_add_bookmark": "ADD CURRENT PATH",
        "hex_viewer_title": "Cyber Hex Viewer",
        "prev_page": "<< PREV PAGE",
        "next_page": "NEXT PAGE >>",
        "btn_close": "CLOSE VIEWPORT",
        "shredder_title": "CYBER SHREDDER - SECURE PURGE",
        "shred_confirm": "WARNING: Securely shred and delete target items?\n\n",
        "btn_cancel": "CANCEL",
        "btn_abort": "ABORT PROTOCOL",
        "copied_status": "Copy operation completed.",
        "moved_status": "Move operation completed.",
        "op_cancelled": "Operation cancelled by operator.",
        "error_occurred": "ERROR OCCURRED: ",
        "target_file": "Target: ",
        "offset": "Offset: ",
        "enter_folder": "Enter Folder Name:",
        "sys_err": "SYSTEM ERROR",
        "prompt_lbl": "SYS_CMD >",
        "welcome_terminal": "==================================================\n   CYBERCOMMANDER KERNEL SHELL v1.0.42_STABLE    \n==================================================\nSYSTEM ACCESS ESTABLISHED. SHELL INTRUSION OK.\nTYPE 'help' FOR A LIST OF CYBER UTILITIES.\n\n",
        "help_txt": "AVAILABLE CYBER COMMANDS:\n  help              - Display this guide.\n  clear             - Flush terminal screen buffer.\n  matrix            - Trigger Matrix Digital Rain visualizer.\n  scan              - Run network port scanning routine.\n  decrypt <target>  - Run cybernetic file decrypter script.\n  * (any system cmd)- Forward execution to operating system shell.\n",
        "matrix_done": "\nMATRIX DOWNLOAD COMPLETE.\n",
        "scan_done": "\nSCAN SEQUENCE COMPLETED.\n",
        "decrypt_done": "\nDECRYPTION INTEGRITY VERIFIED.\n",
        "confirm_title": "PURGE PROTOCOL",
        "input_folder_title": "GENERATE NODE",
        "lbl_status_copy": "Initiating copy...",
        "lbl_status_move": "Initiating move...",
        "lbl_shredding_init": "Initializing File Shredder...",
        "lbl_shredding_done": "SHREDDING COMPLETED SUCCESSFULLY",
        "lbl_shredding_fail": "SHREDDING COMPLETED WITH ERRORS",
        "lbl_shredding_pass": "PASS {}/3 [OVERWRITING DATA]",
        "lbl_shredding_del": "DELETED: ",
        "lbl_shredding_skip": "SKIPPING: ",
        "lbl_shredding_miss": "MISSING: ",
        "pane_stats": "{} / {} files selected [{} / {}]",
        "zip_btn": "EXECUTE ZIP",
        "zip_target": "Target ZIP Filename:",
        "zip_working": "ZIP operations in progress...",
        "cheatsheet_title": "CYBER COMMANDS CHEATSHEET",
        "cs_fkeys": "--- [ FUNCTION KEYS ] ---",
        "cs_alt": "--- [ ALT COMMANDS ] ---",
        "cs_ctrl": "--- [ CTRL COMMANDS ] ---",
        "cs_shift": "--- [ SHIFT COMMANDS ] ---"
    },
    "uz": {
        "f1_help_title": "CYBERCOMMANDER ASOSIY BUYRUQLAR QO'LLANMASI",
        "prop_title": "METAMA'LUMOTLAR XUSUSIYATI",
        "prop_path": "Mutloq yo'l:",
        "prop_size": "Sektor hajmi:",
        "prop_created": "Yaratilgan vaqt:",
        "prop_modified": "Oxirgi o'zgarish:",
        "prop_type": "Tugun turi:",
        "editor_title": "KIBERNETIK MATN TAHRIRLAGICH",
        "editor_save": "O'ZGARISHLARNI SAQLASH",
        "editor_saved": "SAQLANDI. Fayl ma'lumotlari yangilandi.",
        "hidden_toggled": "Yashirin fayllar holati o'zgardi.",
        "flat_toggled": "Yassi ro'yxat ko'rinishi o'zgardi.",
        "swap_panes": "Panellar yo'nalishlari almashtirildi.",
        "tab_opened": "Yangi navigatsiya oynasi (Tab) ochildi.",
        "tab_closed": "Navigatsiya oynasi (Tab) yopildi.",
        "no_selection": "XATO: Ushbu amalni bajarish uchun kamida bitta elementni tanlang.",
        "file_created": "Yangi element muvaffaqiyatli yaratildi.",
        "create_file_prompt": "Yaratiladigan fayl nomini kiriting (masalan, log.txt):",
        "delete_confirm": "DIQQAT: Tanlangan elementlarni butunlay o'chirasizmi? (Savatdan tashqari)\n\n",
        "f3_view": "F1 Help  |  F2 Reread  |  F3 View  |  F4 Edit  |  F5 Copy  |  F6 Move  |  F7 Mkdir  |  F8 Delete",
        "f3_view_btn": "F3 KO'RISH",
        "f4_hash": "F4 TAHRIR",
        "f5_copy": "F5 NUSXA",
        "f6_move": "F6 KO'CHIR",
        "f7_mkdir": "F7 PAPKA",
        "f8_shred": "F8 O'CHIRISH",
        "active_left": "TIZIM TAYYOR. FAOL PANEL: CHAP",
        "active_right": "TIZIM TAYYOR. FAOL PANEL: O'NG",
        "system_ready": "TIZIM TAYYOR.",
        "search_title": "KIBER QIDIRUV TIZIMI",
        "search_pattern": "Qidiruv andozasi (masalan, *.txt):",
        "search_content": "Ichidagi matn (Ixtiyoriy):",
        "search_btn": "QIDIRUVNI BOSHLASH",
        "multi_rename_title": "GURUHLI NOMLASH DASTURI",
        "mr_prefix": "Prefiks andozasi:",
        "mr_suffix": "Suffiks andozasi:",
        "mr_replace_src": "Izlash:",
        "mr_replace_dst": "Bilan almashtirish:",
        "mr_counter": "Hisoblagichni yoqish [1, 2, 3...]:",
        "mr_btn": "NOMLASH PROTOKOLINI BASHARISH",
        "zip_pack_title": "ZIP ARXIPLASH PROTOKOLI",
        "zip_unpack_title": "ZIP ARXIVDAN CHIQARISH",
        "bookmarks_title": "SAQLANGAN YO'LLAR",
        "btn_add_bookmark": "JORIY YO'LNI QO'SHISH",
        "hex_viewer_title": "Kiber Hex Ko'ruvchi",
        "prev_page": "<< OLDINGI",
        "next_page": "KEYINGI >>",
        "btn_close": "OYNAYI YOPISH",
        "shredder_title": "KIBER TOZALAGICH - XAVFSIZ O'CHIRISH",
        "shred_confirm": "DIQQAT: Tanlangan elementlarni qayta tiklab bo'lmaydigan qilib o'chirasizmi?\n\n",
        "btn_cancel": "BEKOR QILISH",
        "btn_abort": "TAYYORLASHNI TO'XTATISH",
        "copied_status": "Nusxalash amali bajarildi.",
        "moved_status": "Ko'chirish amali bajarildi.",
        "op_cancelled": "Amal operator tomonidan bekor qilindi.",
        "error_occurred": "XATOLIK YUZ BERDI: ",
        "target_file": "Fayl: ",
        "offset": "Manzil: ",
        "enter_folder": "Papka nomini kiriting:",
        "sys_err": "TIZIM XATOLIGI",
        "prompt_lbl": "TIZIM_BUYRUG'I >",
        "welcome_terminal": "==================================================\n   CYBERCOMMANDER KERNEL SHELL v1.0.42_STABLE    \n==================================================\nTIZIMGA KIRILDI. QOBIQLI ULANISH YAXSHI.\nYORDAM OLISH UCHUN 'help' BUYRUG'INI YOZING.\n\n",
        "help_txt": "MAVJUD KIBER BUYRUQLAR:\n  help              - Ushbu qo'llanmani ko'rsatish.\n  clear             - Terminal ekranini tozalash.\n  matrix            - Matrix kod yomg'irini ishga tushirish.\n  scan              - Tarmoq portlarini skanerlash simulyatsiyasi.\n  decrypt <target>  - Kiber shifrlashni buzish simulyatsiyasi.\n  * (tizim buyrug'i)- Buyruqni operatsion tizim qobig'iga yuborish.\n",
        "matrix_done": "\nMATRIX YUKLANISHI YAKUNLANDI.\n",
        "scan_done": "\nPORTLARNI SKANERLASH YAKUNLANDI.\n",
        "decrypt_done": "\nDEKODLASH MUVAFFAQIYATLI YAKUNLANDI.\n",
        "confirm_title": "O'CHIRISH PROTOKOLI",
        "input_folder_title": "YANGI PAPKA",
        "lbl_status_copy": "Nusxalash boshlanmoqda...",
        "lbl_status_move": "Ko'chirish boshlanmoqda...",
        "lbl_shredding_init": "Fayl tozalagich tayyorlanmoqda...",
        "lbl_shredding_done": "TOZALASH MUVAFFAQIYATLI YAKUNLANDI",
        "lbl_shredding_fail": "TOZALASH XATOLIKLAR BILAN YAKUNLANDI",
        "lbl_shredding_pass": "BOSQICH {}/3 [KODLARNI QAYTA YOZISH]",
        "lbl_shredding_del": "O'CHIRILDI: ",
        "lbl_shredding_skip": "O'TKAZIB YUBORILDI: ",
        "lbl_shredding_miss": "TOPILMADI: ",
        "pane_stats": "{} / {} fayl tanlandi [{} / {}]",
        "zip_btn": "ZIPNI BAJARISH",
        "zip_target": "ZIP fayl nomi:",
        "zip_working": "ZIP amallari bajarilmoqda...",
        "cheatsheet_title": "KIBER BUYRUQLAR CHEATSHEET",
        "cs_fkeys": "--- [ FUNKSIONAL TUGMALAR ] ---",
        "cs_alt": "--- [ ALT KOMBINATSIYALARI ] ---",
        "cs_ctrl": "--- [ CTRL KOMBINATSIYALARI ] ---",
        "cs_shift": "--- [ SHIFT KOMBINATSIYALARI ] ---"
    },
    "ru": {
        "f1_help_title": "СПРАВОЧНИК ОСНОВНЫХ КОМАНД CYBERCOMMANDER",
        "prop_title": "СВОЙСТВА МЕТАДАННЫХ",
        "prop_path": "Абсолютный путь:",
        "prop_size": "Размер сектора:",
        "prop_created": "Время создания:",
        "prop_modified": "Последнее изменение:",
        "prop_type": "Тип узла:",
        "editor_title": "КИБЕРНЕТИЧЕСКИЙ ТЕКСТОВЫЙ РЕДАКТОР",
        "editor_save": "СОХРАНИТЬ ИЗМЕНЕНИЯ",
        "editor_saved": "СОХРАНЕНО. Синхронизация данных завершена.",
        "hidden_toggled": "Отображение скрытых файлов изменено.",
        "flat_toggled": "Плоский список файлов изменен.",
        "swap_panes": "Пути панелей поменялись местами.",
        "tab_opened": "Новая вкладка навигации открыта.",
        "tab_closed": "Вкладка навигации закрыта.",
        "no_selection": "ОШИБКА: Выберите хотя бы один элемент для этой операции.",
        "file_created": "Новый файл успешно создан.",
        "create_file_prompt": "Введите имя нового файла (например, log.txt):",
        "delete_confirm": "ВНИМАНИЕ: Безвозвратно удалить выбранные элементы? (Мимо корзины)\n\n",
        "f3_view": "F1 Help  |  F2 Reread  |  F3 View  |  F4 Edit  |  F5 Copy  |  F6 Move  |  F7 Mkdir  |  F8 Delete",
        "f3_view_btn": "F3 ПРОСМОТР",
        "f4_hash": "F4 РЕДАКТ",
        "f5_copy": "F5 КОПИЯ",
        "f6_move": "F6 ПЕРЕМЕСТ",
        "f7_mkdir": "F7 ПАПКА",
        "f8_shred": "F8 УДАЛЕНИЕ",
        "active_left": "СИСТЕМА ГОТОВА. АКТИВНЫЙ СЕКТОР: ЛЕВЫЙ",
        "active_right": "СИСТЕМА ГОТОВА. АКТИВНЫЙ СЕКТОР: ПРАВЫЙ",
        "system_ready": "СИСТЕМА ГОТОВА.",
        "search_title": "КИБЕР-ПОИСКОВИК",
        "search_pattern": "Шаблон поиска (например, *.txt):",
        "search_content": "Содержит текст (опционально):",
        "search_btn": "ЗАПУСТИТЬ ПОИСК",
        "multi_rename_title": "ГРУППОВОЕ ПЕРЕИМЕНОВАНИЕ",
        "mr_prefix": "Шаблон префикса:",
        "mr_suffix": "Шаблон суффикса:",
        "mr_replace_src": "Найти текст:",
        "mr_replace_dst": "Заменить на:",
        "mr_counter": "Включить счетчик [1, 2, 3...]:",
        "mr_btn": "ВЫПОЛНИТЬ ПЕРЕИМЕНОВАНИЕ",
        "zip_pack_title": "УПАКОВКА В ZIP",
        "zip_unpack_title": "РАСПАКОВКА ZIP АРХИВА",
        "bookmarks_title": "ЗАКЛАДКИ ПУТЕЙ",
        "btn_add_bookmark": "ДОБАВИТЬ ТЕКУЩИЙ ПУТЬ",
        "hex_viewer_title": "Кибер Hex Просмотрщик",
        "prev_page": "<< НАЗАД",
        "next_page": "ВПЕРЕД >>",
        "btn_close": "ЗАКРЫТЬ ОКНО",
        "shredder_title": "КИБЕР-ШРЕДЕР - БЕЗОПАСНОЕ УДАЛЕНИЕ",
        "shred_confirm": "ВНИМАНИЕ: Безвозвратно уничтожить выбранные элементы?\n\n",
        "btn_cancel": "ОТМЕНА",
        "btn_abort": "ПРЕРВАТЬ ПРОТОКОЛ",
        "copied_status": "Копирование завершено.",
        "moved_status": "Перемещение завершено.",
        "op_cancelled": "Операция отменена оператором.",
        "error_occurred": "ПРОИЗОШЛА ОШИБКА: ",
        "target_file": "Файл: ",
        "offset": "Смещение: ",
        "enter_folder": "Введите имя папки:",
        "sys_err": "СИСТЕМНАЯ ОШИБКА",
        "prompt_lbl": "СИС_КОМАНДА >",
        "welcome_terminal": "==================================================\n   CYBERCOMMANDER KERNEL SHELL v1.0.42_STABLE    \n==================================================\nДОСТУП УСТАНОВЛЕН. ПОДКЛЮЧЕНИЕ К ОБОЛОЧКЕ ОК.\nВВЕДИТЕ 'help' ДЛЯ ПРОСМОТРА КИБЕР-УТИЛИТ.\n\n",
        "help_txt": "ДОСТУПНЫЕ КИБЕР-КОМАНДЫ:\n  help              - Показать это руководство.\n  clear             - Очистить буфер терминала.\n  matrix            - Запустить симуляцию дождя кода Matrix.\n  scan              - Запустить сканирование сетевых портов.\n  decrypt <target>  - Запустить расшифровку файлов.\n  * (системная ком.)- Передать команду командной строке ОС.\n",
        "matrix_done": "\nЗАГРУЗКА МАТРИЦЫ ЗАВЕРШЕНА.\n",
        "scan_done": "\nСКАНИРОВАНИЕ ЗАВЕРШЕНО.\n",
        "decrypt_done": "\nЦЕЛОСТНОСТЬ РАСШИФРОВКИ ПОДТВЕРЖДЕНА.\n",
        "confirm_title": "ПРОТОКОЛ УДАЛЕНИЯ",
        "input_folder_title": "СОЗДАТЬ ПАПКУ",
        "lbl_status_copy": "Запуск копирования...",
        "lbl_status_move": "Запуск перемещения...",
        "lbl_shredding_init": "Инициализация шредера...",
        "lbl_shredding_done": "УНИЧТОЖЕНИЕ ВЫПОЛНЕНО УСПЕШНО",
        "lbl_shredding_fail": "УНИЧТОЖЕНИЕ ЗАВЕРШЕНО С ОШИБКАМИ",
        "lbl_shredding_pass": "ПРОХОД {}/3 [ПЕРЕЗАПИСЬ СЕКТОРОВ]",
        "lbl_shredding_del": "УДАЛЕНО: ",
        "lbl_shredding_skip": "ПРОПУЩЕНО: ",
        "lbl_shredding_miss": "НЕ НАЙДЕНО: ",
        "pane_stats": "Выбрано: {} / {} файлов [{} / {}]",
        "zip_btn": "ВЫПОЛНИТЬ ZIP",
        "zip_target": "Имя ZIP файла:",
        "zip_working": "Выполняются операции ZIP...",
        "cheatsheet_title": "ШПАРГАЛКА КИБЕР-КОМАНД",
        "cs_fkeys": "--- [ ФУНКЦИОНАЛЬНЫЕ КЛАВИШИ ] ---",
        "cs_alt": "--- [ ALT КОМБИНАЦИИ ] ---",
        "cs_ctrl": "--- [ CTRL КОМБИНАЦИИ ] ---",
        "cs_shift": "--- [ SHIFT КОМБИНАЦИИ ] ---"
    }
}

def tr(key):
    lang = QLocale.system().name()[:2].lower()
    if lang not in TEXTS:
        lang = "en"
    return TEXTS[lang].get(key, TEXTS["en"].get(key, key))
